name: Main Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:

  lint:
    uses: ./.github/workflows/reusable-lint.yml

  build-test:
    needs: lint
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      run-tests: true

  sast:
    needs: lint
    uses: ./.github/workflows/reusable-sast.yml

  show-result:
    needs: [lint, build-test , sast ]
    runs-on: ubuntu-latest

    steps:
      - name: Show build and test result
        run: |
          echo "Main pipeline lint result: ${{ needs.lint.outputs.lint_result }}"
          echo "Main pipeline test result: ${{ needs.build-test.outputs.test_result }}"
          echo "Main pipeline SAST result: ${{ needs.sast.outputs.sast_result }}"