name: Main Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:

  lint:
    uses: ./.github/workflows/reusable-lint.yml

  build-test:
    needs: lint
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      run-tests: true

  show-result:
    needs: [lint, build-test]
    runs-on: ubuntu-latest

    steps:
      - name: Show build and test result
        run: |
          echo "Main pipeline lint result: ${{ needs.lint.outputs.lint_result }}"
          echo "Main pipeline test result: ${{ needs.build-test.outputs.test_result }}"