name: Reusable Lint

on:
  workflow_call:
    outputs:
        lint_result:
            description: "Overall result of the lint matrix"
            value: ${{ jobs.lint-summary.outputs.lint_result }}

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a

      - name: Set up Python
        uses: actions/setup-python@06da6279cdbca41027908073e81a4544dc79c06b
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Install Ruff
        run: |
          python -m pip install ruff

      - name: Run Ruff
        run: |
          ruff check app tests

      - name: Run Python syntax check
        run: |
          python -m compileall app tests


  lint-summary:
    if: ${{ always() }}
    needs: lint

    outputs:
        lint_result: ${{ steps.summary.outputs.lint_result }}
    
    runs-on: ubuntu-latest

    steps:
        - name: Generate lint result
          id: summary
          run: |
            if [ "${{ needs.lint.result }}" = "success" ]; then
                echo "All matrix lint jobs passed."
                echo "lint_result=passed" >> "$GITHUB_OUTPUT"
            else
                echo "One or more matrix lint jobs failed. "
                echo "lint_result=failed" >> "$GITHUB_OUTPUT"
                exit 1
            fi